### ISSUE TITLE
Does not work ...

### ISSUE THREAD

**Issue by hatamiarash7** [mosajjal/sniproxy#1]
Hi, there is some problem here.  
DNS request sent to `sniproxy` and routed to the destination successfully, but I think there is not an answer/response to the request.

![Untitled](https://user-images.githubusercontent.com/16325641/156887081-0da7f34a-5b27-474c-99ce-e7fa71529abd.png)

Everything hangs here and does not continue. Finally, we have an SSL error :

![sdfsf](https://user-images.githubusercontent.com/16325641/156887813-85ffe587-cee0-4692-a654-4f879835cdd6.png)

What's the problem?

**Comment by mosajjal** [comment]
hey. just released 0.3.0 to address many reported issues. `sniproxy` should be more stable with the new design. Let me know if that solves this issue. Otherwise I'll take a deeper look :)

**Comment by hatamiarash7** [comment]
Unfortunately the problem is still not solved

**Comment by mosajjal** [comment]
can you share screenshots with the version again please. is it exactly the same error?

**Comment by hatamiarash7** [comment]
Yes, there was no change. I even tested on fresh servers ( Ubuntu server 20 )

**Comment by mosajjal** [comment]
Can you please try the following and provide the output: I made some changes to logging so I can see it better :) 

```
docker run -it --rm -p 80:80 -p 443:443 -p 53:53/udp ghcr.io/mosajjal/sniproxy:v0.4.0 -domainListPath https://raw.githubusercontent.com/freedomofdevelopers/fod/master/domains -publicIP $PUB_IP
```

Cheers,

**Comment by hatamiarash7** [comment]
Now everything works fine 👍 
In this version, we no longer need to define domains as prefixes or suffixes in the previous style?

**Comment by mosajjal** [comment]
actually you're making a valid point. the command I gave you doesn't work because it treats everything as "bypass". The syntax should remain the same (csv with suffix, prefix or fqdn). I'll update the README to reflect that as well. I think this is safe to close though :)

**Comment by hatamiarash7** [comment]
I used binary version and my old list, Maybe that's why there was no problem 😃
