### ISSUE TITLE
how can we actually use this?

### ISSUE THREAD

**Issue by hosnas** [mosajjal/sniproxy#10]
can you explain how we use this?

I run the command on a server. then what should I do?

**Comment by hosnas** [comment]
I added the ip of server in my dns 

however in the server i get errors like this:

 dns: bad A A: "dial" at line: 1:29

**Comment by mosajjal** [comment]
Hi, 

Can you please see if your server has DNS properly set up/

`ping www.google.com`

what does this return?

**Comment by hosnas** [comment]
it returns:

ping: www.google.com: Temporary failure in name resolution

**Comment by hosnas** [comment]
fixed the dns. but still I get the same error

**Comment by mosajjal** [comment]
please paste the command you're running to start `sniproxy`. feel free to mask IP addresses (replace them with XX.XX)

**Comment by hosnas** [comment]
this is the command im using

`docker run -it --rm -p 80:80 -p 443:443 -p 53:53/udp -v "$(pwd):/tmp/" ghcr.io/mosajjal/sniproxy:master --domainListPath https://raw.githubusercontent.com/mosajjal/sniproxy/master/domains.csv`

also tested this:

`docker run -it --rm -p 80:80 -p 443:443 -p 53:53/udp -v "$(pwd):/tmp/" ghcr.io/mosajjal/sniproxy:master --domainListPath https://raw.githubusercontent.com/mosajjal/sniproxy/master/domains.csv --allDomains --bindDnsOverQuic --bindDnsOverTcp --bindDnsOverTls`

btw I tested byosh repo and it seems it worked for me:

`docker run -d -p 53:53/udp -p 443:443 -p 80:80 --net=host -e PUB_IP=206.189.107.74 -e DNS_ALLOW_ALL=YES --name some-byosh mosajjal/byosh:latest`

**Comment by mosajjal** [comment]
looks like you're not providing `--publicIP` as a parameter and your network prevents `sniproxy` to auto-detect it. find out your server's real IP by doing this:
`curl ifconfig.me` and use the ipv4 as `--publicIP`.

**Comment by hosnas** [comment]
thank you very much. now it works

I have a question. 

I enabled --allDomains options. Now from all of my traffics, incoming and outgoing, is everything behind this proxy? or for example maybe some ports isn't supported?

**Comment by mosajjal** [comment]
SNI is a TLS (HTTPS) extension so sniproxy will only work on HTTP(S) traffic. for redirecting the entire traffic over, consider using a VPN.
