### ISSUE TITLE
SSL Certificates

### ISSUE THREAD

**Issue by x004A** [mosajjal/sniproxy#11]
It is my sincere pleasure to thank you for creating this DNS-proxy application. 
When I tried to pull from an HTTPS repository, such as http://archive.ubuntu.com/ubuntu, I received these errors.
 
`Certificate verification failed: The certificate is NOT trusted. The name in the certificate does not match the expected.  Could not handshake: Error in the certificate verification. [IP: MY_PUBLIC_IP 443]
`

`Could not handshake: The TLS connection was non-properly terminated. [IP: MY_PUBLIC_IP 443]`

Does this app accept SSL certificates? If so, could you please tell me where they should be entered?

**Comment by x004A** [comment]
![image](https://user-images.githubusercontent.com/46030348/194370557-a5c42e85-226e-4707-9ab1-9395275c656a.png)

`docker run -it --rm -p 80:80 -p 443:443 -p 53:53/udp -v "$(pwd):/tmp/" ghcr.io/mosajjal/sniproxy --domainListPath https://raw.githubusercontent.com/mosajjal/sniproxy/master/domains.csv --bindDnsOverTls --publicIP MY_PUBLIC_IP`

**Comment by mosajjal** [comment]
Hi there. glad you're enjoying it :) 

does this error happen to most domains or only certain URLs? it looks like Ubuntu's servers are doing something that I might've not anticipated and that's why we're seeing the error. Also, 91.189.91.38 seems to be unreachable from your server.

**Comment by x004A** [comment]
This IP address is one of the Ubuntu repositories and can be reached manually (apt update) in this dns-proxy machine.
The majority of domains with HTTP already work, but HTTPS doesn't.

Also, I tried using [byosh](https://github.com/mosajjal/byosh), everything was fine, but IPv6 didn't work

Does SNI-proxy support IPv6?

**Comment by mosajjal** [comment]
I'll test Ubuntu update and try to see if I can replicate the issue. and yes sniproxy should be able to handle ipv6 just fine. let me know if there's any issues there.

**Comment by mosajjal** [comment]
hey @x004A try 0.8.x see if that solves your problem. if not, please paste the logs here. I added more logs so it'll be easier to pinpoint the issue
