### ISSUE TITLE
curios case , i need some help

### ISSUE THREAD

**Issue by kooroshkdt2** [mosajjal/sniproxy#114]
Hi
i'm trying pull docker from http base repo(insecure)
some how sniproxy doesnt work with docker on http 
but works perfectly with https 
i test it same server and scenario just replaced sniproxy port 80 http with haproxy tcp type and it works flawlessly 
can you assist me on this problem ? 

Best Regards

**Comment by mosajjal** [comment]
Hi, 

can you please provide the logs in debug mode and share. anonymize the IP addresses if need be.

Cheers,

**Comment by mosajjal** [comment]
I'll close this for now, feel free to re-open with the detailed logs.
