### ISSUE TITLE
Absence of Public IPv4 or IPv6 Will Result in Panic (master branch)

### ISSUE THREAD

**Issue by moh53n** [mosajjal/sniproxy#119]
Hi Ali, Thanks for your great project!  
I was testing your project for my personal network, but I had random unrecoverable halts with the latest released version (v2.0.4), so I tried compiling the master branch.  
The random halt problem seems to be resolved on the master branch (I'm still testing), but I encountered the following panic:  
```
panic: ParseAddr(""): unable to parse IP

goroutine 20 [running]:
net/netip.MustParseAddr(...)
        /usr/lib/go-1.22/src/net/netip/netip.go:136
github.com/mosajjal/sniproxy/v2/pkg.isSelf(0x12d1220, {{0xc0000ba380?, 0x12d1220?}, 0xc000130018?})
        /root/sni/sniproxy/pkg/https.go:19 +0x1cc
github.com/mosajjal/sniproxy/v2/pkg.handle443(0x12d1220, {0xdaa570, 0xc000120598}, {{0xda07c8, 0xc0000442c0}, 0xff, {0x0, 0x0}, {0xc000218800, 0x12, ...}, ...})
        /root/sni/sniproxy/pkg/https.go:79 +0x669
created by github.com/mosajjal/sniproxy/v2/pkg.RunHTTPS in goroutine 12
        /root/sni/sniproxy/pkg/https.go:168 +0xbb
```

It seems when the host doesn't have a public IPv4 or IPv6, [this line](https://github.com/mosajjal/sniproxy/blob/9f3ad051131f9dc5e1746fc1c1c265cbb3c6dff5/pkg/https.go#L19) causes a panic.

**Comment by mosajjal** [comment]
Hi,

Thanks mate! And also thanks for your contributions :)

Does this problem persist even after you hard-code public IPv4/IPv6 in the config?

**Comment by moh53n** [comment]
Glad I could help!
No, it seems resolved when I hard-code a public IPv6 in the config.
I also forgot to mention this panic only happens when the server is processing a HTTP(s) request.

**Comment by mosajjal** [comment]
added another check for this. can you please confirm if the latest `master` commit fixes this panic.

**Comment by moh53n** [comment]
Unfortunately the panic still happens since in my case, I have IPv4 but no IPv6.    
[You're checking both with &&](https://github.com/mosajjal/sniproxy/commit/60bbcd7c240285ef0976597a40e6bc626fdc05e1):
```if c.PublicIPv4 == "" && c.PublicIPv6 == "" {```

**Comment by mosajjal** [comment]
I have time to refactor this code a bit. it's too messy as it is hence the issues. I think the condition is correct, but the bootstrapping needs to have better options when the VPS doesn't offer ipv6.

**Comment by mosajjal** [comment]
v2.1.2 fixes this issue with the caveat of having to set the option `preferred_version` to `ipv4only` in the config, which is not the default value. Have a test and let me know :)

**Comment by moh53n** [comment]
I can confirm the problem is fixed now. Thank you!
