### ISSUE TITLE
disabling systemd-resolved

### ISSUE THREAD

**Issue by x004A** [mosajjal/sniproxy#12]
Following this [instruction](https://gist.github.com/zoilomora/f7d264cefbb589f3f1b1fc2cea2c844c), I released port 53 after disabling systemd-resolved. There is no way to look up domains and repositories on the machine. 

When using SNI Proxy, can I enable the system resolver? 

`docker: Error response from daemon: Get "https://ghcr.io/v2/": dial tcp: lookup ghcr.io on [::1]:53: read udp [::1]:49747->[::1]:53: read: connection refused.`

**Comment by mosajjal** [comment]
Hi. 

Depending on your Linux distribution, you can set another set of DNS servers in your network config. simplest solution is to edit `/etc/resolv.conf` (make sure it's not symlinked to a non-existing path) and add your nameservers there. Although there's a chance that there are other services in your box overriding what you put in there. Take a look at [Arch's documentation](https://wiki.archlinux.org/title/systemd-resolved) for more details.

**Comment by x004A** [comment]
Thanks a lot. Using this [instruction](https://www.linuxuprising.com/2020/07/ubuntu-how-to-free-up-port-53-used-by.html), I was able to resolve it on Ubuntu
