### ISSUE TITLE
dns目前仅支持udp53，有考虑过将来添加tls，tcp...等方式吗？

### ISSUE THREAD

**Issue by viagram** [mosajjal/sniproxy#2]
讲真，这款工具很好用。也许只是我人品的原因，我一个新IP我用udp53三到10天不等，就会被干扰，要么失败，要么解析到错误的IP。
如果可能希望将来能添加tls，tcp...等方式。
谢谢！

**Comment by mosajjal** [comment]
Hi there. sorry I don't speak Mandarin. Are you looking for DNS Over TLS or something along those lines for upstream DNS?

**Comment by viagram** [comment]
> 

Sorry, I can't speak English either. I mean, I hope your program can support TLS, TCP and other security methods in addition to the conventional UDP 53 method when parsing DNS, because it is often disturbed when using udp53 in China.

**Comment by mosajjal** [comment]
added some options in v0.5.0, please test and let me know if that solves your issue :)

**Comment by viagram** [comment]
> added some options in v0.5.0, please test and let me know if that solves your issue :)

/usr/bin/sniproxy -bindDnsOverTls -domainListPath /etc/sniproxy.domains -publicIP 103.83.188.96 -bindDnsOverTcp
INFO[0000] Loading the domain from file/url to a list
INFO[0000] (re)loading File: /etc/sniproxy_domains.conf
INFO[0000] /etc/sniproxy_domains.conf loaded with 380 lines
INFO[0000] Started UDP DNS on 0.0.0.0:53 -- listening
INFO[0000] Started TCP DNS on 0.0.0.0:53 -- listening
INFO[0000] Started DoT on 0.0.0.0:853 -- listening
FATA[0000] Failed to start server: listen tcp :53: bind: address already in use

**Comment by viagram** [comment]
> added some options in v0.5.0, please test and let me know if that solves your issue :)

/usr/bin/sniproxy -bindDnsOverTls -domainListPath /etc/sniproxy_domains.conf -publicIP 103.83.188.96 -bindDnsOverTcp
INFO[0000] Loading the domain from file/url to a list
INFO[0000] (re)loading File: /etc/sniproxy_domains.conf
INFO[0000] /etc/sniproxy_domains.conf loaded with 380 lines
INFO[0000] Started UDP DNS on 0.0.0.0:53 -- listening
INFO[0000] Started TCP DNS on 0.0.0.0:53 -- listening
INFO[0000] Started DoT on 0.0.0.0:853 -- listening
FATA[0000] Failed to start server: listen tcp :53: bind: address already in use

The log shows that it listened to port 853, but it didn't succeed.
The TCP port of 53 shows that it has been occupied

**Comment by viagram** [comment]
> > added some options in v0.5.0, please test and let me know if that solves your issue :)
> 
> /usr/bin/sniproxy -bindDnsOverTls -domainListPath /etc/sniproxy_domains.conf -publicIP 103.83.188.96 -bindDnsOverTcp INFO[0000] Loading the domain from file/url to a list INFO[0000] (re)loading File: /etc/sniproxy_domains.conf INFO[0000] /etc/sniproxy_domains.conf loaded with 380 lines INFO[0000] Started UDP DNS on 0.0.0.0:53 -- listening INFO[0000] Started TCP DNS on 0.0.0.0:53 -- listening INFO[0000] Started DoT on 0.0.0.0:853 -- listening FATA[0000] Failed to start server: listen tcp :53: bind: address already in use
> 
> The log shows that it listened to port 853, but it didn't succeed. The TCP port of 53 shows that it has been occupied

After investigation, it was found to be main Go line 209 port error, correct to 853 and then operate normally.
However, dig + TLS will not return results, while dig + TCP can return results normally.
`			serverTls := &dns.Server{Addr: ":53", Net: "tcp-tls", TLSConfig: tlsConfig}`
`			serverTls := &dns.Server{Addr: ":853", Net: "tcp-tls", TLSConfig: tlsConfig}`

**Comment by mosajjal** [comment]
ah yes I can see the typo. will push a new version shortly

**Comment by viagram** [comment]
> ah yes I can see the typo. will push a new version shortly

TLS mode seems to have some problems. The test results are as follows:
`dig @dns_ server google.com`  normal
`dig @dns_ server google.com`  normal
`dig @dns_ server google.com`  no return

**Comment by mosajjal** [comment]
might be because of self-signed cert? not sure how to test that out tbh. right now dns-over-tcp solves your problem though right?

**Comment by viagram** [comment]
> might be because of self-signed cert? not sure how to test that out tbh. right now dns-over-tcp solves your problem though right?

Yes, at present, only TCP-TLS mode is not working properly.

**Comment by viagram** [comment]
> might be because of self-signed cert? not sure how to test that out tbh. right now dns-over-tcp solves your problem though right?

In https://zerossl.com can apply for IP address certificate. I hope you can take the time to check the tcp-tls mode.
thanks!

**Comment by viagram** [comment]
Have already been solved

**Comment by mosajjal** [comment]
hey there. just saw your PR being closed. is that what did the trick for you at the end? keen to see how you solved it so I can add it to the code

**Comment by viagram** [comment]
save the nation by a devious path
(PR)
