### ISSUE TITLE
how to configure and use sniproxy in readme file

### ISSUE THREAD

**Issue by Mehrdad3** [mosajjal/sniproxy#20]
We need document !! how to run and use this repository ?
I've just ran the podman-docker script in this project but couldn't find how to configure other things and use this project as a smart Dns proxy
thanks

**Comment by mosajjal** [comment]
hey. what do you want to use sniproxy for? it's meant to be reasonably simple and for not-so-big use-cases. I'm looking into building it into a one-click deploy on Vultr so I'll try to make a YouTube video when that happens. In the meantime, feel free to raise a PR with docs :)

**Comment by Mehrdad3** [comment]
Hi ali, I want it to be something like shecan , as I knew you have been trying to impelement something like shecan project! isn't ?
but after deploy it on ubuntu i didn't know which configuration file have to edit! for example can I have it as a public Dns server but limit it for especial public ip of my home xbox or just some of my friends?

**Comment by mosajjal** [comment]
I added an auto installer for Ubuntu/Debian servers as well as some notes to the readme. hopefully this will solve your problem.
