### ISSUE TITLE
dig times out

### ISSUE THREAD

**Issue by 62w71st** [mosajjal/sniproxy#28]
Hi @mosajjal , 

I'm test driving the proxy. I have a vultr server setup with the instructions in the cmdline, and dns enabled for udp and tcp. But dig times out from my machine:
```
dig www.google.com @95.179.163.92      

; <<>> DiG 9.10.6 <<>> www.google.com @95.179.163.92
;; global options: +cmd
;; connection timed out; no servers could be reached
```

I can ping www.google.com from the server: 
```
ping www.google.com 
PING www.google.com(fra07s63-in-x2004.1e100.net (2a00:1450:4001:80e::2004)) 56 data bytes
```

And the server is listening on 53: 
```
sudo lsof -i :53 
COMMAND    PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
sniproxy 38230 root    3u  IPv4  53499      0t0  UDP 95.179.163.92.vultrusercontent.com:44251->dns.google:domain 
sniproxy 38230 root   11u  IPv6  53511      0t0  UDP *:domain 
sniproxy 38230 root   12u  IPv6  53512      0t0  TCP *:domain (LISTEN)
```

digging www.google.com from the server:
```
dig www.google.com 

; <<>> DiG 9.18.1-1ubuntu1.3-Ubuntu <<>> www.google.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 28137
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;www.google.com.			IN	A

;; ANSWER SECTION:
www.google.com.		135	IN	A	142.250.185.228

;; Query time: 0 msec
;; SERVER: 9.9.9.9#53(9.9.9.9) (UDP)
;; WHEN: Thu Mar 02 16:23:12 UTC 2023
;; MSG SIZE  rcvd: 59
```

There is no firewall setup on Vultr. 

Do you know what could be wrong here?

**Comment by mosajjal** [comment]
> There is no firewall setup on Vultr. 

can you confirm if `iptables` and `ufw` etc are not running on the VM you have? you can always start by running `dig` on the server itself and see if it resolves.

**Comment by 62w71st** [comment]
Thank you! ufw was indeed the issue. `sudo ufw disable`  solved the issue. 

And interestingly, when I dig from my machine now, I always get my server ip for all names, which is expected, as all traffic now needs to go through the sni proxy.
