### ISSUE TITLE
dns: bad AAAA AAAA

### ISSUE THREAD

**Issue by yaser-k** [mosajjal/sniproxy#38]
level=ERROR msg= service=dns !BADKEY="dns: bad AAAA AAAA: \"\\n\" at line: 1:22"

I think it cause because of absent "publicIPv6" parameter in config?

**Comment by mosajjal** [comment]
which version are you using?

**Comment by yaser-k** [comment]
check both latest and master of docker image

**Comment by mosajjal** [comment]
pushed a tiny change just now. can you check again?

**Comment by yaser-k** [comment]
that error is gone but I see  this error now although it work fine and return the IP anyway. 

level=ERROR msg= service=dns !BADKEY="response for query 26817 was truncated. consider using a different protocol (TCP) for large queries"

 level=ERROR msg= service=dns !BADKEY="dns: overflowing header size"

**Comment by mosajjal** [comment]
did some more cleanup. hopefully the errors go away. let me know if there's any issues.
