### ISSUE TITLE
geoip option

### ISSUE THREAD

**Issue by yaser-k** [mosajjal/sniproxy#39]
I set this on my config file
"geoipInclude": "IR",

but the docker log this message on start

level=INFO msg=GeoIP exclude=[]
level=INFO msg=GeoIP include=[]

I suspect if it read the config?

**Comment by mosajjal** [comment]
when using geoipInclude or geoipExclude, `geoipPath` becomes mandatory and has to be provided. I changed the logging that makes it more clear in `master`. try putting the `geoipPath` and see if that solves it. you can copy paste it from the help menu :)

**Comment by yaser-k** [comment]
I still have this log
level=INFO msg=GeoIP exclude=[]
level=INFO msg=GeoIP include=[]
level=INFO msg="Using an upstream SOCKS5 proxy" address=172.17.0.1:10808
level=INFO msg="Loading the domain from file/url" service=dns
level=INFO msg="(re)loading File" service=dns file=/tmp/domains.csv
level=INFO msg="Started TCP DNS" service=dns host=0.0.0.0 port=53
level=INFO msg="Loading the domain from file/url" service=geoip
level=INFO msg="domain list is a URL, trying to fetch" service=geoip

my geoipPath is this. is it correct?

"geoipPath": "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/Country.mmdb",

**Comment by mosajjal** [comment]
the last log message indicates that your machine is having trouble downloading the mmdb. for testing, you can download the `Country.mmdb` file separately and point `sniproxy` to the local path rather than the URL.

**Comment by yaser-k** [comment]
test with docker master and local file still have same issue

 level=INFO msg=GeoIP exclude=[]
 level=INFO msg=GeoIP include=[]
 level=INFO msg="Using an upstream SOCKS5 proxy" address=172.17.0.1:10808
 level=INFO msg="Loading the domain from file/url" service=dns
 level=INFO msg="(re)loading File" service=dns file=/tmp/domains.csv
 level=INFO msg="/tmp/domains.csv loaded with 0 prefix, 3 suffix and 0 fqdn" service=dns
 level=INFO msg="Started TCP DNS" service=dns host=0.0.0.0 port=53
 level=INFO msg="Started UDP DNS" service=dns host=0.0.0.0 port=53
 level=INFO msg="Loading the domain from file/url" service=geoip
 level=INFO msg="(re)loading File: " service=geoip !BADKEY=/tmp/Country.mmdb
 level=INFO msg="geolocation database loaded" service=geoip !BADKEY=0

**Comment by mosajjal** [comment]
I'll close this to encourage everyone to join the discussion (#42) and test v2 together.
