### ISSUE TITLE
Proxying fail until restart service

### ISSUE THREAD

**Issue by MortyTech** [mosajjal/sniproxy#40]
Hi Ali
I'm in Iran and I want to make my shecan ! everything works nicely and has no problem, but after a few minutes service will not work, I mean sni daemon is up and running but on client side no response, In this situation I can get a response from sni server by nslookup command but when I use Links or any other browser to open a site its not possible unit I restart the service and this loop is continuous

**Comment by mosajjal** [comment]
Hi!

please run `sniproxy` and save the logs somewhere and attach it here so I can take a look. can't really help without it. Make sure that you delete/mask any IP addresses that you don't want to be public.

**Comment by MortyTech** [comment]
I installed the snipproxy command by go and its works correctly, it seems this problem is shown only in the scripting install way, thank Ali.

**Comment by mosajjal** [comment]
yep there are/were some errors in the `install.sh`. hopefully v2 provides a better config experience.
