### ISSUE TITLE
DNS is not returning correct IP

### ISSUE THREAD

**Issue by prooshani** [mosajjal/sniproxy#41]
Thanks @mosajjal for this nice work.

I am running sniproxy on a VPS and it looks to be working. There are some issues with installation though. tlskey and tlscert tags changed in documentations as well as sniproxy service while the interactive installer sets wrong tags (certpah and keypath which looks from older versions) inside the configurations.

Anyway, I have changed them using `sudo systemctl edit --full sniproxy`

After fixing some issues finally the sniproxy starts to work, at least it looks like this.
If I use dig on the sniproxy server it returns correct IP's but, if I use the sniproxy's server IP as a DNS on my router or other dns clients all the queries returning the sniproxy's server IP. Is it as expected or I have missed something in here?
If it means to be like this, how it would work then?

**Comment by mosajjal** [comment]
Hi.

take a look at #33, might be a related issue in Iran. the midboxes sometimes rewrite the DNS response and replace it with the "real" IP which is problematic. 

I've suggested some methods of 1) confirming and 2) troubleshooting the issue. if it's the same, let's follow it up in #33 or open a discussion for it, if it's different let me know so we can continue here.

**Comment by prooshani** [comment]
> Hi.
> 
> take a look at #33, might be a related issue in Iran. the midboxes sometimes rewrite the DNS response and replace it with the "real" IP which is problematic.
> 
> I've suggested some methods of 1) confirming and 2) troubleshooting the issue. if it's the same, let's follow it up in #33 or open a discussion for it, if it's different let me know so we can continue here.

It looks quiet similar to the #33 and I will continue there for better follow up and troubleshootings.

Thanks anyway
