### ISSUE TITLE
source IP address in log

### ISSUE THREAD

**Issue by yaser-k** [mosajjal/sniproxy#53]
My sniproxy server is under heavy DDoS Attack. I set geoip like  allowed: [US]. but it seems that sniproxy recieve request and then response with something like "http response with status_code 403 Forbidden service=http"
Also I can't see source IP on log that I get with following command
 docker  logs -f  --details sniproxy

**Comment by yaser-k** [comment]
I have this config for geoip
  geoip:
    enabled: true 
    priority: 10
    blocked:
    allowed: [US]
    path: /tmp/Country.mmdb
    refresh_interval: 24h0m0s

but I get this log when docker start. why it say " 0 bytes" in line 3?

INF app/acl/geoip.go:62 > Loading the domain from file/url acl=geoip
INF app/acl/geoip.go:82 > (re)loading File: /tmp/Country.mmdb acl=geoip
INF app/acl/geoip.go:88 > geolocation database with 0 bytes loaded acl=geoip

**Comment by mosajjal** [comment]
hi. yep there was a bug in reading the file. the URL was/is ok. it's fixed in the latest commit.
