### ISSUE TITLE
return sniproxy ip for domain that not listed

### ISSUE THREAD

**Issue by yaser-k** [mosajjal/sniproxy#56]
I get "returned sniproxy address for domain dns.msftncsi.com. service=dns"
domain:
    enabled: true
and dns.msftncsi.com or msftncsi.com is not in domains.csv

**Comment by mosajjal** [comment]
would you mind sharing your domains.csv? also please share the debug log (omit any IP addresses and domains that you're not comfortable sharing of course)

**Comment by yaser-k** [comment]
I attach debug log, domain list and I think the nslookup from 8.8.8.8 for msftncsi.com screenshot explain the unexpected behaviour. 
![nslookup](https://github.com/mosajjal/sniproxy/assets/49610613/9de3c7bd-7da9-4d86-86cc-bd7734175238)
[sniproxy-debug.txt](https://github.com/mosajjal/sniproxy/files/11583965/sniproxy-debug.txt)
[domains.csv](https://github.com/mosajjal/sniproxy/files/11583962/domains.csv)

**Comment by mosajjal** [comment]
looks like www.msftncsi.com translates to www.msftncsi.com.edgesuite.net, and edgesuite.net is in your `domains.csv` as a suffix, and that's how it's getting through sniproxy rather than direct


![image](https://github.com/mosajjal/sniproxy/assets/10158936/1182fd70-dad6-43a9-aaf8-29543098cb9a)

**Comment by yaser-k** [comment]
But for msftncsi.com itself there is just NS records and no A record but sniproxy return it’s ip for that too.

**Comment by mosajjal** [comment]
what I would do to test is, start with a smaller `domains.csv`, and see if the problem exists. if it does, you can always run `tcpdump` to see what does your DNS look like.

**Comment by yaser-k** [comment]
Ok. I remove all entries from domain.csv except "ipify.org.,suffix" now when I query "msftncsi.com" it behave normally.
it return nothing for A record and return NS correctly. 
but when I put all domain in domain.csv it somehow think "msftncsi.com" is in list (that is not) and also return sniproxy IP for A record although the domain have no A record at all.
I can't find which entry cause this. try removing "microsoft.com" and it didn't work.
tcpdump didn't give me more info

`dig @X.X.X.X msftncsi.com

; <<>> DiG 9.18.1-1ubuntu1.3-Ubuntu <<>> @X.X.X.X msftncsi.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 59549
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;msftncsi.com.                  IN      A

;; Query time: 147 msec
;; SERVER: X.X.X.X#53(X.X.X.X) (UDP)
;; WHEN: Sun May 28 12:38:34 UTC 2023
;; MSG SIZE  rcvd: 30`

` dig @X.X.X.X msftncsi.com NS

; <<>> DiG 9.18.1-1ubuntu1.3-Ubuntu <<>> @X.X.X.X msftncsi.com NS
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 37943
;; flags: qr rd; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;msftncsi.com.                  IN      NS

;; ANSWER SECTION:
msftncsi.com.           18935   IN      NS      ns1-34.azure-dns.com.
msftncsi.com.           18935   IN      NS      ns2-34.azure-dns.net.
msftncsi.com.           18935   IN      NS      ns3-34.azure-dns.org.
msftncsi.com.           18935   IN      NS      ns4-34.azure-dns.info.

;; Query time: 204 msec
;; SERVER: X.X.X.X#53(X.X.X.X) (UDP)
;; WHEN: Sun May 28 12:36:31 UTC 2023
;; MSG SIZE  rcvd: 215`

**Comment by yaser-k** [comment]
Ok.I give up and just delete all domains except the one I need for xbox service. it seem that return correct result for msftncsi.com.
But I wonder which domain it match to. perhaps additional log in debug level to show which entry of domain.csv match?

**Comment by mosajjal** [comment]
yep agreed that better logging for CNAME and which domain triggered the rule makes sense. I'll leave this open as an improvement

**Comment by mosajjal** [comment]
have a look at v2.0.3 in debug mode. hopefully better logging there and it'll help resolve some of the issues.
