### ISSUE TITLE
arm64 docker image

### ISSUE THREAD

**Issue by RaminMT** [mosajjal/sniproxy#58]
Hi
Is it possible to add arm64 architecture for docker image in pipeline? so we can also use this on arm based devices?

Thanks

**Comment by mosajjal** [comment]
Hi. 

yeah shouldn't be too hard to add a new package in GHCR. I'll look into it.

**Comment by mosajjal** [comment]
Done for `master`. 

![image](https://github.com/mosajjal/sniproxy/assets/10158936/0becaf53-2d98-410e-8080-5afa8fa18cc7)

next release will have all as well.
