### ISSUE TITLE
public_ipv4 empty result error

### ISSUE THREAD

**Issue by yaser-k** [mosajjal/sniproxy#72]
If public_ipv4 is not set (for example in a LAN implementation) the DNS service returns no record. I had to set it to the private IP of the server to sniporxy working (return record).

error if public_ipv4 isn't set:
*** No internal type for both IPv4 and IPv6 Addresses (A+AAAA) records available for

**Comment by mosajjal** [comment]
public_ipv4 is meant to be "public" not private. Can't see this be a bug. If `public_ipv4` is not set, you will see an error in the logs before sniproxy starts as well. LAN implementation in general is not part of `sniproxy` today.
