### ISSUE TITLE
allow multiple upstream DNS

### ISSUE THREAD

**Issue by yaser-k** [mosajjal/sniproxy#73]
It would be a good idea if we could set multiple upstream DNS IPs for redundancy.

**Comment by mosajjal** [comment]
No plan to further upstream DNS within `sniproxy`, but there is a plan to allow `sniproxy` to natively use OS's DNS as upstream DNS. Which means redundancy as well as protocols such as dnscrypt will be possible. Otherwise sniproxy will become too big to maintain.
