### ISSUE TITLE
connection to private IP or self ignored service=https

### ISSUE THREAD

**Issue by yaser-k** [mosajjal/sniproxy#74]
why is connection to private IP ignored? I want to implement sniproxy in a lan and therefore the IP that sniproxy returns to clients is a private range.

**Comment by mosajjal** [comment]
in https://github.com/mosajjal/sniproxy/blob/5e34eee5b2eaeda69aba39447c3d605250607ff6/https.go#L57, any connection to RFC1918 addresses are blocked. This is mainly implemented to prevent rebinding attacks or SSRF against the VPS infrastructure on the open internet. I can consider an option switch to allow local IPs for `sniproxy` but it'll be off by default.

**Comment by yaser-k** [comment]
That would be great if we have such option

**Comment by mosajjal** [comment]
#80
