### ISSUE TITLE
sniproxy https stop responding after a few response

### ISSUE THREAD

**Issue by yaser-k** [mosajjal/sniproxy#76]
I set up this sniproxy with upstream socks5
upstream_dns: "tcp://127.0.0.1:54"  (its a long story but it works)
upstream_socks5: "socks5://127.0.0.1:10808"

The upstream socks and upstream DNS are another process on the same machine. Every time I stop and start sniproxy.service it works for a few seconds, answers some https responses correctly, and then stops responding.
When it stops responding I check the following modules separately:
upstream DNS: working. test with: dig +tcp @127.0.0.1 -p 54 example.com
upstream socks5 working. test with: curl  -x socks5h://127.0.0.1:10808 https://api.ipify.org?format=json
sniproxy DNS is working - dig @127.0.0.1 -p 53  example.com ( example.com is on the domains.csv so return sniproxy IP)

but the https module of sniproxy does not respond anymore.
test with: curl https://api.ipify.org?format=json --resolve api.ipify.org:443:sni_proxy_IP
when restart sniproxy (systemctl restart  sniproxy.service) then it starts responding again for a few seconds and the above test also work.

When I get "lsof -i -P -n | grep  sniproxy" I see a lot of CLOSE_WAIT connections from clients, don't know if it is relevant.
TCP sniproxy_ip:443->client_ip:port (CLOSE_WAIT)

If you need sniproxy logs I can send it but I don't know where to look.

**Comment by mosajjal** [comment]
please send the logs in `debug` mode but make sure you remove any sensitive data (IP etc) from it.

**Comment by yaser-k** [comment]
here is the log from start service until it stop responding to https.
[sniproxy log.txt](https://github.com/mosajjal/sniproxy/files/12573553/sniproxy.log.txt)

**Comment by mosajjal** [comment]
I can't see any issues in the logs. I don't see this issue in any of my other instances as well. Reckon the issue might not be from `sniproxy`

**Comment by yaser-k** [comment]
Do other instances use upstream socks? I think the problem is how sniproxy manage socks connection. I think sniproxy create a new socks connection for every request. am i right?

**Comment by mosajjal** [comment]
yes I believe so. I'll do more testing with SOCKS5 upstream and will let you know. can I ask which implementation of SOCKS5 you're using as upstream?

**Comment by yaser-k** [comment]
I am using xray core that implement my inbound SOCKS5 and outbound connection.
https://github.com/XTLS
here is my related config for xray
`
{
    "log": {"access": "/var/log/xray/access.log","error": "/var/log/xray/error.log","loglevel": "warning"},
	"dns": {
		"servers": ["8.8.8.8","8.8.4.4"],
		"queryStrategy": "UseIPv4",
		"disableCache": false,
		"disableFallback": false,
		"disableFallbackIfMatch": false,
		"tag": "dns-in"
	},
    "inbounds": [
		{"tag": "in-socks","udp": false,"ip": "127.0.0.1","port": 10808,"protocol": "socks",
			"settings": {"auth": "noauth"}
		},
		{
			"tag": "dns-in",
			"port": 54,
			"protocol": "dokodemo-door",
			"settings": {
				"network": "tcp,udp",
				"address": "8.8.8.8",
				"port": 53
			}
		}
	],
    "outbounds": [
		{"tag": "dns-out","protocol": "dns",
			"settings":{
				"network": "tcp",
				"address": "8.8.8.8",
				"port": 53,
				"nonIPQuery": "drop"
			},
			"proxySettings": {"tag": "out1"}
		},
		{"tag": "out1",
			//any protocole that xray support 
		}   
        },
		{"tag": "direct","protocol": "freedom"}  //you could also use direct for outbound if it works for you
	],
	"routing": {
		"rules": [
			{"type": "field","inboundTag": ["dns-in","in-socks"],"port": "53", "outboundTag": "dns-out"},
			{"type": "field","inboundTag": ["in-socks"],"outboundTag": "out1"}	
		]
   }
}
`
and this is my related settings in sniproxy config:
`
  upstream_dns: "tcp://127.0.0.1:54"
  upstream_dns_over_socks5: false
  upstream_socks5: "socks5://127.0.0.1:10808"
`

**Comment by mosajjal** [comment]
I did some tests using `brook` as the upstream `SOCKS5`. I can confirm performance issues when `upstream_dns_over_socks5: true` but when `upstream_dns_over_socks5: false`, everything works as expected. would you be able to replicate your tests with [`brook`](https://github.com/txthinking/brook/releases/tag/v20230606)?

**Comment by yaser-k** [comment]
I test the brook like sniproxy --socks5--> brook --socks5--> xray. this implementation seems to work more stable that I think because of some sort of socks connection management in brook.
Although I get these errors time to time
could not connect to target with error: read tcp 127.0.0.1:18822->127.0.0.1:10810: i/o timeout service=https
[DNS] Empty DNS response for ***********.com. service=https

**Comment by mosajjal** [comment]
connection pooling is something I'm willing to consider. need to finish up some clean ups and make sure the dns client itself is working properly first.

**Comment by mosajjal** [comment]
This should be fixed now especially for DNS. I'll close this, but feel free to re-open and I'll look into it.
