### ISSUE TITLE
At present, UDP, TCP, DoT and DoQ have been implemented, and the DoH is still missing. Can you add this on next version?

### ISSUE THREAD

**Issue by viagram** [mosajjal/sniproxy#8]
At present, UDP, TCP, DoT and DoQ have been implemented, and the DoH is still missing. Can you add this on next version?

**Comment by viagram** [comment]
Looking forward to your update

**Comment by mosajjal** [comment]
hey mate. sure. Need to check to see what libraries exist. if you have a rough PR happy to look at it and make adjustments :)

**Comment by mosajjal** [comment]
added a simple doh upstream support. have a look to see if that works for you. the server side will be a bit more complicated since both HTTPS traffic and DoH traffic will be on port 443 TCP and multiplexing that over TCP and TLS is a bit of work.

**Comment by viagram** [comment]
Thank you for your work and look forward to DoH's server-side launch  :)

**Comment by mosajjal** [comment]
will close this. server DoH implementation is gonna be too much work and will potentially disrupt security of `sniproxy`.
