### ISSUE TITLE
broken install.sh

### ISSUE THREAD

**Issue by mosajjal** [mosajjal/sniproxy#87]

**Comment by mehdiabr** [comment]
Hello.  When I try to install the installation script, I get error 522.  Of course, I am not sure if this error is from my server  or from somewhere else. Please check it

**Comment by mosajjal** [comment]
522 error should be resolved now. but there are a couple other issues as well. please test again and send me the error if you encounter any.

**Comment by mehdiabr** [comment]
Hello. Thank you, yes, this problem is solved, but now when in the installation phase, I get to select the option "dns over tcp or tls..." if I select "y", it gives this error:
    (Error: stat /opt/sniproxy/sniproxy.yaml: No such file or directory.)
    And if I choose "N", the installation continues but the "status" shows me this: 'active: failed'

**Comment by mosajjal** [comment]
should be fixed now. but need a few minutes (hours?) before Github raw content cache clears up and the command actually returns the correct `installer.sh`. let me know if all is fixed so we can close this one out

**Comment by mehdiabr** [comment]
Solved.🤩my god. A.mosajjal you are wonderful. I have been looking for this tutorial for more than 2 years but I failed to implement it due to its complexity, but you have made this difficult method in the form of a simple script. Thank you very much,good luck.

**Comment by mosajjal** [comment]
good luck to you too :)
