### ISSUE TITLE
Some websites not opening, dot and doh usage

### ISSUE THREAD

**Issue by mehdiabr** [mosajjal/sniproxy#88]
Hi engineer.  Sorry, I am an amateur user and I have 3 questions and problems.
1_ In the script installation stage, is it better to enable the "dns over tcp or tls or quic" option or not? and if we choose 'dot', do we have to do something else?
2_My service is successfully installed and running, but there are many sites that don't open!! Of course,what is important and necessary for me is Google domains.
3_In some apps, such as the "intra" app or in the 'private dns' section of our phone's settings, we have to enter an 'url address'. Is it also possible to use the domain address instead of the 'IP' in clients when using sniproxy?

**Comment by mosajjal** [comment]
Hi brother.

1) if you're running this from Iran, it depends on the device you're using this with. for Android, DoH (Dns over HTTPS) is what's used. refer to the documentation on how to enable it. you need to enable DoH in an ACL setting rather than in the wizard. 

2) feel free to send me the logs produced by `sniproxy`. keep in mind that the logs might contain sensitive information like your IP address so please remove them before sending it here. 

3) refer to the answer in 1 for that. you should specify a subdomain, get a certificate configure `sniproxy` to use that certificate in order for your device to use it. 

hopefully this helps.

**Comment by mehdiabr** [comment]
Hi. I have 2 servers.  On both servers, the script was installed successfully.  But when I check its status, it says "failed". I send their log file. 
[1Logntsniproxy.txt](https://github.com/mosajjal/sniproxy/files/13257480/1Logntsniproxy.txt)
[2Logfrsniproxy.txt](https://github.com/mosajjal/sniproxy/files/13257481/2Logfrsniproxy.txt)
Also I did not understand what you mean about the possibility of installing "doh" and the document related to it.  If possible, leave the link related to it.

**Comment by mosajjal** [comment]
when you go through the auto-install wizard, it creates a minimal configuration file located here:

`/opt/sniproxy/config.yaml`

if you want to change/enhance the config, or add Dns-over-HTTPS, you need to edit that file. A complete template of the configuration file including comments/documentation is available [here](https://github.com/mosajjal/sniproxy/blob/master/cmd/sniproxy/config.defaults.yaml). hopefully this helps :)

**Comment by mehdiabr** [comment]
Thanks, i will check it. But a strange thing happened recently, I have 2 servers in which I successfully installed this script, but when I check its status, it says "active: failed". What could be the reason?  I have already sent you the login file, I will send it again.
[Logsninl3.txt](https://github.com/mosajjal/sniproxy/files/13311899/Logsninl3.txt)

**Comment by mehdiabr** [comment]
Thanks.I have 2 problems. 
1_During the installation, when I want to give the path of the certificate and key, I get an error.(error 1:22 invalid input text "/etc/letsencrypt/.......), Please  see the screenshot. 
![InShot_20231207_183014770](https://github.com/mosajjal/sniproxy/assets/148278523/be1fc6f7-15d1-4b8b-8c7c-12b1ccce0d0f)
2_ Also, when I take a dns leak test, I see dns from another country!! To solve this problem, can I use dnss of the same country as my server instead of 9.9.9.9?

**Comment by mosajjal** [comment]
both these issues (1 and 2) should be fixed now. for 3, I think you need to test against `https://ident.me` etc to get your public facing IP. Google doesn't solely rely on IP to geolocate you so there might be additional steps that you need to take.

**Comment by mehdiabr** [comment]
After the last changes, if we give the path of the certificate file &key to the script during installation, it will be installed, but it will not be executed(running: failed)!  You can check it yourself. Of course,no problem, I set them in the config file after installation. but "doh" service does not work!! please look at my config file to see where the problem is. 
[Sniproxyconfig.txt](https://github.com/mosajjal/sniproxy/files/13660151/Sniproxyconfig.txt)

**Comment by mosajjal** [comment]
can you please also share the service logs as well?

**Comment by mehdiabr** [comment]
Hi, was my 'doh' settings correct? I don't know enough about Linux.And after running the journal -u sniproxy command, I copied these logs.(Both files are same and related to the same time). 
[Sni journal log.txt](https://github.com/mosajjal/sniproxy/files/13695798/Sni.journal.log.txt)
[Snijournallog.txt](https://github.com/mosajjal/sniproxy/files/13695824/Snijournallog.txt)

**Comment by mehdiabr** [comment]
The 2 main problems of this service at the moment are: 
1_The "doh" function of the service does not work. 
2And that the service does not respond after some time (sites cannot be opened) while the service is running.!!

**Comment by mosajjal** [comment]
I'll close this since there's been many changes from a year ago. please re-open with specifics and we'll go from there.
