### ISSUE TITLE
Is IPv6 rotation supported?

### ISSUE THREAD

**Issue by haig233** [mosajjal/sniproxy#93]
A website I want to proxy will be blocked if I access a fixed address multiple times. I want to add a large number of IPv6 to the VPS and then run SniProxy. Does SniProxy support ipv6 rotation? Does it automatically select an ipv6 address every time it is used as a proxy?

**Comment by mosajjal** [comment]
both `ipv4` and `ipv6` rotation is something I would like to take a look at soon.

**Comment by haig233** [comment]
https://github.com/oliverkirk-sudo/ipv6-pool-tool-socks

Here is a repository for your reference. This is a random egress using the address prefix bound to the network card to provide an ipv6 proxy pool.

**Comment by mosajjal** [comment]
the attached repo doesn't work at scale. I'm working on providing upstream ipv6 support. After that, source IP rotation will be added based on a given subnet. There will be some OS level issues that needs to be solved before it can work.

**Comment by mosajjal** [comment]
this should be supported in the latest version.
