### ISSUE TITLE
Domain list

### ISSUE THREAD

**Issue by haig233** [mosajjal/sniproxy#96]
I started using sniproxy today and found that the management of domain name lists is still too cumbersome, whether it is collection or sorting.

Coincidentally, today I discovered an interesting project in the v2fly community: [domain-list-community](https://github.com/v2fly/domain-list-community). There are thousands of domain name rules compiled by community maintainers, which can be used directly, for example: 
https://github.com/v2fly/domain-list-community/blob/master/data/openai
There are already domain names of all openai services compiled and maintained by community members, including CDN and API, which will save a lot of trouble.

I hope to be able to introduce the corresponding package, and like v2fly's v2ray project, I can directly manage domain names in a similar way to  `geosite:openai`  and decide which domains I proxy.

**Comment by mosajjal** [comment]
the format of those lists are a bit different. I can potentially write a helper script that gets that `dat` file and converts it into a CSV file that's ingest-able by `sniproxy`.

**Comment by haig233** [comment]
Yes, it seems that golang does not have a public corresponding package. Maybe you can only check the main.go of domain-list-community to see how it generates the dat file to reversely write the parsing code.
