### ISSUE TITLE
GIthub Problem

### ISSUE THREAD

**Issue by hamedyosefian** [mosajjal/sniproxy#98]
Hi .. i run this on us server of digital ocean and worked fine 
but github return this error :
[09:59:59.703] Response code 401 (Unauthorized)

some time worked some time this errror 
how to config that to github direct instead proxy

**Comment by mosajjal** [comment]
Hi. not sure what does your current configuration look like, but you can use a domain ACL with a CSV file with custom allowlist. this is an example config if you want to know more:
https://github.com/mosajjal/sniproxy/blob/master/cmd/sniproxy/config.defaults.yaml
